// Copyright © 2024 Brent Tunnicliff <brent@tunnicliff.dev>

import Testing

@testable import AdventOfCode

struct Day07Tests {
    private let testData = """
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ...............
        .....^.^.^.....
        ...............
        ....^.^...^....
        ...............
        ...^.^...^.^...
        ...............
        ..^...^.....^..
        ...............
        .^.^.^.^.^...^.
        ...............
        """

    @Test
    func testPart1() {
        let challenge = Day07(data: testData)
        #expect(challenge.part1() == 21)
    }

    @Test
    func testPart2() async {
        let challenge = Day07(data: testData)
        #expect(challenge.part2() == 40)
    }
}
